# Generated by Django 5.0.1 on 2024-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_name', models.CharField(max_length=16)),
                ('measure', models.CharField(max_length=16)),
                ('data', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_name', models.CharField(max_length=16)),
                ('measure', models.CharField(max_length=16)),
                ('data', models.CharField(max_length=16)),
            ],
        ),
    ]
