# Generated by Django 5.0.6 on 2024-06-20 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditydata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='data',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
