# Generated by Django 5.0.6 on 2024-06-24 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_app', '0002_alter_humiditydata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tempdata',
            name='data',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
